Repository almsam/Numerical-Analysis-code, pull requests merged in 2024-09, with the labels that each got.

#15 Rm body
  README.md
Labels: documentation, in review

#22 Cleaned up and did some simple bug fixing
  Plot finder.py
Labels: enhancement

#23 Implemented user-defined function regression and added function manipulation capabilities
  Plot finder.py
Labels: enhancement, in review

#25 Modified Plot finder.py and updated .gitignore to exclude Vim swap files
  .gitignore
  Plot finder.py
Labels: enhancement, in review
